# Autogenerated wrapper script for mosquitto_client_jll for x86_64-w64-mingw32
export libmosquitto

using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("mosquitto_client")
JLLWrappers.@declare_library_product(libmosquitto, "libmosquitto.dll")
function __init__()
    JLLWrappers.@generate_init_header(OpenSSL_jll)
    JLLWrappers.@init_library_product(
        libmosquitto,
        "bin\\libmosquitto.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
